{
  "formatVersion": "1.1",
  "component": {
    "group": "net.mamby.androidkit",
    "module": "compose",
    "version": "0.1.63",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "net.mamby.androidkit",
          "module": "foundation",
          "version": {
            "requires": "0.1.63"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.09.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.5.0-alpha29"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "compose-0.1.63.aar",
          "url": "compose-0.1.63.aar",
          "size": 1489533,
          "sha512": "36ef71efea7a3afb9df15db4da8782b593efe92cd57d7b79332b504c390969241949d496b8abf1d7ed7dbdebbdd778e64dc278e988ff92bb04c3948654020169",
          "sha256": "cc9ce557c68b603a8d35acda7b4426c8599d164fe3d498bdc40d651cc0e06d00",
          "sha1": "d332661903198c0decf5cee7a9f7d094204ab66d",
          "md5": "f688f085edfe7e964fe3d6d7ebcb2418"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.14.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "net.mamby.androidkit",
          "module": "foundation",
          "version": {
            "requires": "0.1.63"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.09.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.5.0-alpha29"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "compose-0.1.63.aar",
          "url": "compose-0.1.63.aar",
          "size": 1489533,
          "sha512": "36ef71efea7a3afb9df15db4da8782b593efe92cd57d7b79332b504c390969241949d496b8abf1d7ed7dbdebbdd778e64dc278e988ff92bb04c3948654020169",
          "sha256": "cc9ce557c68b603a8d35acda7b4426c8599d164fe3d498bdc40d651cc0e06d00",
          "sha1": "d332661903198c0decf5cee7a9f7d094204ab66d",
          "md5": "f688f085edfe7e964fe3d6d7ebcb2418"
        }
      ]
    }
  ]
}
