{
  "formatVersion": "1.1",
  "component": {
    "group": "net.mamby.androidkit",
    "module": "compose",
    "version": "0.1.53",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "net.mamby.androidkit",
          "module": "foundation",
          "version": {
            "requires": "0.1.53"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.09.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.5.0-alpha29"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "compose-0.1.53.aar",
          "url": "compose-0.1.53.aar",
          "size": 1447081,
          "sha512": "de618359f6e0ae845824a827fe7ae4daf291d8cedca0403d7663c4c4ab91316b11b44c6e232129e09e26ba735aa4709a7b99b9c0fa6db29f7c1b0efff95687e0",
          "sha256": "4e7710c1fe9ed0f39dcb6b819e12cc684f416bfd0d52c8d0f8dc36f923d8d9ec",
          "sha1": "d9740599ea74a122b96ec28ae1573420b7b5b3d0",
          "md5": "d004d2b7886d4597aa38b4653799187b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.14.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "net.mamby.androidkit",
          "module": "foundation",
          "version": {
            "requires": "0.1.53"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.09.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.5.0-alpha29"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "compose-0.1.53.aar",
          "url": "compose-0.1.53.aar",
          "size": 1447081,
          "sha512": "de618359f6e0ae845824a827fe7ae4daf291d8cedca0403d7663c4c4ab91316b11b44c6e232129e09e26ba735aa4709a7b99b9c0fa6db29f7c1b0efff95687e0",
          "sha256": "4e7710c1fe9ed0f39dcb6b819e12cc684f416bfd0d52c8d0f8dc36f923d8d9ec",
          "sha1": "d9740599ea74a122b96ec28ae1573420b7b5b3d0",
          "md5": "d004d2b7886d4597aa38b4653799187b"
        }
      ]
    }
  ]
}
