{
  "formatVersion": "1.1",
  "component": {
    "group": "net.mamby.androidkit",
    "module": "compose",
    "version": "0.1.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "net.mamby.androidkit",
          "module": "foundation",
          "version": {
            "requires": "0.1.68"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.09.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.5.0-alpha29"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "compose-0.1.68.aar",
          "url": "compose-0.1.68.aar",
          "size": 1506453,
          "sha512": "5f27cec727e08d37072ca15c2778409d68d63d06fcd4ec4ba5cbe2a53363fc50717f9b218550a884c6a0585d535210a862233e3653f66c609351ceca43e03636",
          "sha256": "486e19553d2448d76eefe512837434d6d8ced64f0fbf37a285d4422705ad3466",
          "sha1": "36b56a951603c17f388ae7d14a469bc9d4a8da01",
          "md5": "1a28919a93fe14e59d88ee495671d44f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.14.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "net.mamby.androidkit",
          "module": "foundation",
          "version": {
            "requires": "0.1.68"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.09.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.5.0-alpha29"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "compose-0.1.68.aar",
          "url": "compose-0.1.68.aar",
          "size": 1506453,
          "sha512": "5f27cec727e08d37072ca15c2778409d68d63d06fcd4ec4ba5cbe2a53363fc50717f9b218550a884c6a0585d535210a862233e3653f66c609351ceca43e03636",
          "sha256": "486e19553d2448d76eefe512837434d6d8ced64f0fbf37a285d4422705ad3466",
          "sha1": "36b56a951603c17f388ae7d14a469bc9d4a8da01",
          "md5": "1a28919a93fe14e59d88ee495671d44f"
        }
      ]
    }
  ]
}
