{
  "formatVersion": "1.1",
  "component": {
    "group": "net.mamby.androidkit",
    "module": "compose",
    "version": "0.1.57",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "net.mamby.androidkit",
          "module": "foundation",
          "version": {
            "requires": "0.1.57"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.09.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.5.0-alpha29"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "compose-0.1.57.aar",
          "url": "compose-0.1.57.aar",
          "size": 1431398,
          "sha512": "72cccfaf876600bb861da1f13e61305574a52ae06461416e08e2738167e26b2982df2c1be930f4e094da735cba520df414b824e85185fbc1855f02dc12c15cd3",
          "sha256": "4dba3f8f8e8dfc300f1e876d06e8b46764ed305e124879a78febb9bd1caa63fe",
          "sha1": "9a3455095a9e93e6a268e22a3f61c252c16160bf",
          "md5": "e1c7644fcc3e774f116c5ff8e04ec6d7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.14.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "net.mamby.androidkit",
          "module": "foundation",
          "version": {
            "requires": "0.1.57"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2026.09.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.5.0-alpha29"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "compose-0.1.57.aar",
          "url": "compose-0.1.57.aar",
          "size": 1431398,
          "sha512": "72cccfaf876600bb861da1f13e61305574a52ae06461416e08e2738167e26b2982df2c1be930f4e094da735cba520df414b824e85185fbc1855f02dc12c15cd3",
          "sha256": "4dba3f8f8e8dfc300f1e876d06e8b46764ed305e124879a78febb9bd1caa63fe",
          "sha1": "9a3455095a9e93e6a268e22a3f61c252c16160bf",
          "md5": "e1c7644fcc3e774f116c5ff8e04ec6d7"
        }
      ]
    }
  ]
}
